name: Auto Create Tasks for BA
on:
  issues:
    types: [labeled]

jobs:
  create-subtasks:
    if: github.event.label.name == 'kind::story'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create BE, FE, and QC Tasks
        run: |
          # Chúng ta thêm tham số --repo để chỉ định đích danh kho Timind
          gh issue create --title "[BE] ${{ github.event.issue.title }}" --body "Thuộc Story: #${{ github.event.issue.number }}" --label "team::BE" --repo ${{ github.repository }}
          gh issue create --title "[FE] ${{ github.event.issue.title }}" --body "Thuộc Story: #${{ github.event.issue.number }}" --label "team::FE" --repo ${{ github.repository }}
          gh issue create --title "[QC] ${{ github.event.issue.title }}" --body "Thuộc Story: #${{ github.event.issue.number }}" --label "team::QC" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
